<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

| **Term**   |                       **Brief description**                       |
|------------|:-----------------------------------------------------------------:|
| Subsetting |           To select a subset of data in a list or array           |
| Indexing   |       Referring to an element of an iterable by its position      |
| Slicing    | Getting a subset of elements from an iterable using its positions |
| Masking    |                   Filter or handle unwanted data                  |

# Exercise 2

In [115]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [116]:
x=np_array_2d[:,0]
x=np.array(x, dtype=int)
x

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [117]:
x=x%2
x

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [119]:
array = x > 0
array

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [123]:
list(np_array_2d[array][:,1])

['A', 'C', 'E', 'G', 'I']