<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# 1 Lists, Arrays & Dictionaries

## Let’s compare

### Python Lists

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

Order matters

### Numpy Arrays

In [3]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Order matters

### Dictionaries

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow", "Tony Stark": "Iron Man", "Stephen Strange": "Doctor Strange"
}

Order does not matter

## Accessing data from a list (or array)

In [6]:
py_real_names[1]

'Tony Stark'

In [7]:
py_super_names[1]

'Iron Man'

In [8]:
py_super_names[-1]

'Doctor Strange'

## Accessing data from a dictionary

In [9]:
superhero_info['Natasha Romanoff']

'Black Widow'

In [10]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [11]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [14]:
superhero_info.items()

dict_items([('Natasha Romanoff', 'Black Widow'), ('Tony Stark', 'Iron Man'), ('Stephen Strange', 'Doctor Strange')])

Used to access key value pairs

## Higher dimensional lists

In [15]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Lists vs. Arrays

## Size

In [17]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [18]:
len(py_list_2d)

10

In [19]:
len(np_array_2d)

10

In [20]:
np_array_2d.shape

(10, 2)

## Arrays are fussy about type

In [21]:
py_list = [1,2,'A']
np_array = np.array(py_list)

In [22]:
py_list

[1, 2, 'A']

In [23]:
np_array

array(['1', '2', 'A'], dtype='<U11')

Arrays only tolerate a single type.

## Adding a number

In [24]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

In [25]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [26]:
np_array + 10

array([11, 12, 13, 14, 15])

## Adding another list

In [27]:
list_1 = [1,2,3,4,5]
list_2 = [10,20,30,40,50]

array_1 = np.array(list_1)
array_2 = np.array(list_2)

In [28]:
list_1 + list_2 #Concatenation of both lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [29]:
array_1 + array_2 #Addition of each element, element-wise operation

array([11, 22, 33, 44, 55])

## Multiplying by a Number

In [30]:
list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)

In [32]:
list_1*2 #Adding the list onto itself

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [33]:
array_1*2 #Multiplying each element

array([ 2,  4,  6,  8, 10])

## Squaring

In [34]:
list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)

In [35]:
list_1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [36]:
array_1**2 #Squaring each element

array([ 1,  4,  9, 16, 25])

## Asking questions

In [37]:
list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)

In [38]:
list_1 == 3 #Asking whether the list [1,2,3,4,5] is equal to 3

False

In [39]:
list_1 > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [42]:
array_1 == 3 #Compares each element in the array and see whether it equals to 3

array([False, False,  True, False, False])

In [43]:
array_1 > 3 #Compares each element in the array and see whether it is greater than 3

array([False, False, False,  True,  True])

## Mathematics

In [44]:
list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)

In [45]:
sum(list_1)

15

In [46]:
max(list_1)

5

In [47]:
min(list_1)

1

In [48]:
array_1.sum()

15

In [49]:
array_1.max()

5

In [50]:
array_1.min()

1

In [51]:
array_1.mean()

3.0

In [52]:
array_1.std()

1.4142135623730951