<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# Subsetting: Indexing and Slicing

## Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list

In [3]:
x[0]

'a1'

In [4]:
x[-1]

'j10'

In [5]:
x[0:3]

['a1', 'b2', 'c3']

In [6]:
x[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [7]:
x[1:6:2] #Index 1 to 5 in steps of 2

['b2', 'd4', 'f6']

In [8]:
x[5:] #Index 5 onwards

['f6', 'g7', 'h8', 'i9', 'j10']

In [9]:
x[:5] #Index 0 to Index 4

['a1', 'b2', 'c3', 'd4', 'e5']

In [10]:
x[5:2:-1] #Index 5 to Index 2 from the back

['f6', 'e5', 'd4']

In [11]:
x[::-1] #Reverse the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

Slicing with [i:j] means that the slice starts with the index i but ends on the index j-1

## Arrays only | Subsetting by masking

In [12]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [14]:
np_array[my_mask] #Show the values that are True

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[~(np_array > 3)]  # '~' means 'NOT', showing False values

array([1, 2, 3])

In [18]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means and, combining 1 mask with another, shows values when both masks are true

array([4, 5, 6, 7])

In [19]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR', shows values when either mask is true

array([ 1,  2,  9, 10])

Masking only works with numpy arrays

~ is not, | is or, & is and

## Lists & Arrays in 2D | Indexing & Slicing

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [22]:
print(py_list_2d[3])
print(np_array_2d[3])

[4, 'D']
['4' 'D']


In [25]:
print(py_list_2d[3][0])
print(np_array_2d[3, 0]) #only 1 single pair of square brackets

4
4


In [27]:
print(py_list_2d[:3]) #first 3 elements
print(np_array_2d[:3])

[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


In [29]:
print(py_list_2d[:3][0]) #Index 0 of first 3 elements
print(np_array_2d[:3, 0]) #Gives first of the list from np_array_2d[:3]

[1, 'A']
['1' '2' '3']


In [30]:
print(py_list_2d[3:6][0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


Numpy arrays slicing syntax is more intuitive than lists, and are good for fast math operations, but lists are easier and more efficient in growing.

## Growing lists

In [31]:
x=[1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [33]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [34]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [35]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

Execution speeds are different, append() runs about 1.5x faster than the rest

In [37]:
x=[1,2,3]
x+=[4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [39]:
x=[1,2,3]
x.extend([4,5,6]) #Add each element in list to x
x

[1, 2, 3, 4, 5, 6]

In [40]:
x=[1,2,3]
x.append([4,5,6]) #Adds the list [4,5,6] to the next element of the list x
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## Tuples

Immutable sequences, cannot change their variables after creation

In [41]:
tpl = (1,2,3)

In [42]:
tpl[0]

1

In [43]:
tpl[0]=2

TypeError: 'tuple' object does not support item assignment

In [44]:
tpl[0]+=3

TypeError: 'tuple' object does not support item assignment

## Be VERY careful when copying

In [45]:
x=[1,2,3]
y=x
z=x 

Deep copy, the locations of y and z are the same as the location of x. If the values of x change, the values of y and z will change as well.

In [46]:
x=[1,2,3]
y=x.copy()
z=y.copy()

Shallow copy, only the values of x and y are copied over